
# All paths relative to this config file

generators:
  generator_c:
    enabled: true
    paths:
      output_header: ../../../firmware/src/can/can_endpoints.h
      output_impl: ../../../firmware/src/can/can_endpoints.c
    c_header_includes:
    - src/common.h
    c_impl_includes:
    - <string.h>
    - src/adc/adc.h
    - src/system/system.h
    - src/encoder/encoder.h
    - src/observer/observer.h
    - src/motor/motor.h
    - src/controller/controller.h
    - src/nvm/nvm.h
  generator_rst:
    enabled: true
    paths:
      output_file: ../../../docs/api/reference.rst

