
# All paths relative to this config file

generators:
  generator_c:
    enabled: true
    paths:
      output_header: ../../../firmware/src/can/endpoints.h
      output_impl: ../../../firmware/src/can/endpoints.c
    c_includes:
    - src/common.h
  generator_rst:
    enabled: true
    paths:
      output_file: ../../../docs/api/reference.rst

