
name: tm
version: 0.9.0
remote_attributes:
  - name: protocol_hash
    dtype: uint32
    c_getter: _avlos_get_proto_hash
    summary: The Avlos protocol hash.
  - name: uid
    dtype: uint32
    c_getter: system_get_uid
    summary: The unique device ID, unique to each PAC55xx chip produced.
  - name: Vbus
    dtype: float
    unit: volt
    c_getter: system_get_Vbus
    summary: The bus voltage.
  - name: temp
    dtype: float
    unit: degC
    c_getter: adc_get_mcu_temp
    summary: The internal temperature of the PAC55xx MCU.
  - name: errors
    dtype: uint8
    c_getter: system_get_errors
    summary: Any system errors, as a bitmask
  - name: save_config
    summary: Save configuration to non-volatile memory.
    c_caller: nvm_save_config
    dtype: void
    arguments: []
  - name: erase_config
    summary: Erase the config stored in non-volatile memory and reset the device.
    c_caller: nvm_erase
    dtype: void
    arguments: []
  - name: reset
    summary: Reset the device.
    c_caller: system_reset
    dtype: void
    arguments: []
  - name: cycles
    remote_attributes:
      - name: total
        dtype: uint32
        c_getter: Scheduler_GetTotalCycles
        summary: Total processor cycles in a single PWM cycle.
      - name: busy
        dtype: uint32
        c_getter: Scheduler_GetBusyCycles
        summary: Busy processor cycles in a single PWM cycle.
  - name: controller
    remote_attributes:
      - name: state
        dtype: uint8
        c_getter: controller_get_state
        c_setter: controller_set_state
        summary: The state of the controller.
      - name: mode
        dtype: uint8
        c_getter: controller_get_mode
        c_setter: controller_set_mode
        summary: The control mode of the controller.
      - name: errors
        dtype: uint8
        c_getter: controller_get_errors
        summary: Any controller errors, as a bitmask
      - name: position
        remote_attributes:
          - name: setpoint
            dtype: float
            unit: tick
            c_getter: controller_get_pos_setpoint_user_frame
            c_setter: controller_set_pos_setpoint_user_frame
            summary: The position setpoint.
          - name: p_gain
            dtype: float
            c_getter: controller_get_pos_gain
            c_setter: controller_set_pos_gain
            summary: The proportional gain of the position controller.
      - name: velocity
        remote_attributes:
          - name: setpoint
            dtype: float
            unit: tick/sec
            c_getter: controller_get_vel_setpoint_user_frame
            c_setter: controller_set_vel_setpoint_user_frame
            summary: The velocity setpoint.
          - name: limit
            dtype: float
            unit: tick/sec
            c_getter: controller_get_vel_limit
            c_setter: controller_set_vel_limit
            summary: The velocity limit.
          - name: p_gain
            dtype: float
            c_getter: controller_get_vel_gain
            c_setter: controller_set_vel_gain
            summary: The proportional gain of the velocity controller.
          - name: i_gain
            dtype: float
            c_getter: controller_get_vel_integrator_gain
            c_setter: controller_set_vel_integrator_gain
            summary: The integral gain of the velocity controller.
          - name: deadband
            dtype: float
            c_getter: controller_get_vel_integrator_deadband
            c_setter: controller_set_vel_integrator_deadband
            rst_target: integrator-deadband
            summary: The deadband of the velocity integrator. A region around the position setpoint where the velocity integrator is not updated.
      - name: current
        remote_attributes:
          - name: Iq_setpoint
            dtype: float
            unit: ampere
            c_getter: controller_get_Iq_setpoint_user_frame
            c_setter: controller_set_Iq_setpoint_user_frame
            summary: The Iq setpoint.
          - name: Iq_limit
            dtype: float
            unit: ampere
            c_getter: controller_get_Iq_limit
            c_setter: controller_set_Iq_limit
            summary: The Iq limit.
          - name: Iq_estimate
            dtype: float
            unit: ampere
            c_getter: controller_get_Iq_estimate_user_frame
            summary: The Iq estimate.
          - name: bandwidth
            dtype: float
            c_getter: controller_get_I_bw
            c_setter: controller_set_I_bw
            summary: The current controller bandwidth.
          - name: Iq_p_gain
            dtype: float
            c_getter: controller_get_Iq_gain
            summary: The current controller proportional gain.
      - name: calibrate
        summary: Calibrate the device.
        c_caller: controller_calibrate
        dtype: void
        arguments: []
      - name: idle
        summary: Set idle mode, disabling the driver.
        c_caller: controller_idle
        dtype: void
        arguments: []
      - name: position_mode
        summary: Set position control mode.
        c_caller: controller_position_mode
        dtype: void
        arguments: []
      - name: velocity_mode
        summary: Set velocity control mode.
        c_caller: controller_velocity_mode
        dtype: void
        arguments: []
      - name: current_mode
        summary: Set current control mode.
        c_caller: controller_current_mode
        dtype: void
        arguments: []
  - name: comms
    remote_attributes:
    - name: can
      remote_attributes:
      - name: rate
        dtype: uint32
        c_getter: CAN_get_kbit_rate
        c_setter: CAN_set_kbit_rate
        rst_target: api-can-rate
        summary: The baud rate of the CAN interface.
      - name: id
        dtype: uint32
        c_getter: CAN_get_ID
        c_setter: CAN_set_ID
        summary: The ID of the CAN interface.
  - name: motor
    remote_attributes:
      - name: R
        dtype: float
        unit: ohm
        c_getter: motor_get_phase_resistance
        c_setter: motor_set_phase_resistance
        summary: The motor Resistance value.
      - name: L
        dtype: float
        unit: henry
        c_getter: motor_get_phase_inductance
        c_setter: motor_set_phase_inductance
        summary: The motor Inductance value.
      - name: pole_pairs
        dtype: uint8
        c_getter: motor_get_pole_pairs
        c_setter: motor_set_pole_pairs
        summary: The motor pole pair count.
      - name: type
        #values: [HIGH_CURRENT, GIMBAL]
        dtype: uint8
        c_getter: motor_get_is_gimbal
        c_setter: motor_set_is_gimbal
        summary: The type of the motor. Either high current or gimbal.
      - name: offset
        dtype: float
        c_getter: motor_get_user_offset
        c_setter: motor_set_user_offset
        summary: User-defined offset of the motor.
      - name: direction
        dtype: uint8
        c_getter: motor_get_user_direction
        c_setter: motor_set_user_direction
        summary: User-defined direction of the motor.
      - name: errors
        dtype: uint8
        c_getter: motor_get_errors
        summary: Any motor/calibration errors, as a bitmask
      # - name: phase_currents
      #   remote_attributes:
      #     - name: U
      #       dtype: float
      #       unit: ampere
      #       c_getter: motor_get_IU
      #       summary: Measured current in phase U.
      #     - name: V
      #       dtype: float
      #       unit: ampere
      #       c_getter: motor_get_IV
      #       summary: Measured current in phase V.
      #     - name: W
      #       dtype: float
      #       unit: ampere
      #       c_getter: motor_get_IW
      #       summary: Measured current in phase W.
  - name: encoder
    remote_attributes:
      - name: position_estimate
        dtype: float
        unit: ticks
        c_getter: observer_get_pos_estimate
        summary: The filtered encoder position estimate.
      - name: type
        #values: [INTERNAL, HALL]
        dtype: uint8
        c_getter: encoder_get_type
        c_setter: encoder_set_type
        summary: The encoder type. Either INTERNAL or HALL.
      - name: bandwidth
        dtype: float
        unit: rad/s
        c_getter: observer_get_bw
        c_setter: observer_set_bw
        summary: The encoder observer bandwidth.
      - name: errors
        dtype: uint8
        c_getter: encoder_get_errors
        summary: Any encoder errors, as a bitmask
  - name: traj_planner
    remote_attributes:
      - name: max_accel
        dtype: float
        unit: ticks/s
        c_getter: planner_get_max_accel
        c_setter: planner_set_max_accel
        summary: The trajectory planner max acceleration.
      - name: max_decel
        dtype: float
        unit: ticks/second/second
        c_getter: planner_get_max_decel
        c_setter: planner_set_max_decel
        summary: The trajectory planner max deceleration.
      - name: max_vel
        dtype: float
        unit: ticks/second
        c_getter: planner_get_max_vel
        c_setter: planner_set_max_vel
        summary: The trajectory planner max cruise velocity.
      - name: move_to
        summary: Move to target position respecting velocity and acceleration limits.
        c_caller: planner_move_to_vlimit
        dtype: void
        arguments:
          - name: pos_setpoint
            dtype: float
      - name: move_to_tlimit
        summary: Move to target position respecting time limits for each sector.
        c_caller: planner_move_to_tlimit
        dtype: void
        arguments:
          - name: pos_setpoint
            dtype: float
      - name: errors
        dtype: uint8
        c_getter: planner_get_errors
        summary: Any errors in the trajectory planner, as a bitmask
